language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install pylint

script:
  - find -name "*.py" -not -path "./src/migrations/versions/*" -not -path "./venv/*" -not -path "./tests/*" | xargs pylint
