language: python

python:
  - 3.7

env:
  - BFF_POSTGRES_DBNAME=bff

services:
  - postgresql

install:
  - pip install -r requirements-dev.txt

before_script:
  - psql -c "CREATE DATABASE bff;" -U postgres
  - cd src/ && ./migrations/migrate.sh && cd ../

script:
  - flake8
  - py.test --cov --cov-config=setup.cfg
  - mypy app.py

after_success:
  - codecov
